RECAPTCHA_SITE_KEY_V3 = "6LdoXckhAAAAAIGpoFflYCx7x36jGdtWxn_tSsSd"
RECAPTCHA_SECRET_KEY_V3 = "********"
RECAPTCHA_SITE_KEY_V2 = "6Lfmx3UiAAAAAMkhGO0yOxvGNskO3srFo5RCFSVL"
RECAPTCHA_SECRET_KEY_V2 = "*******"
MIN_SCORE = 0.7
